{
 "title": "DateTime Service Dashboard",
 "description": "Monitoring dashboard for DateTime Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "all {{endpoint}} {{status_code}}"
    }
   ]
  },
  {
   "title": "CPU consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"postgres\"}[1m])) * 100",
     "legendFormat": "postgres"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"redis\"}[1m])) * 100",
     "legendFormat": "redis"
    }
   ]
  },
  {
   "title": "Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "avg {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "0.95 {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "0.99 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Percentage of Missed Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rate(cache_misses_total[1m]) / (rate(cache_hits_total[1m]) + rate(cache_misses_total[1m])) * 100",
     "legendFormat": "holidays-cached"
    }
   ]
  }
 ]
}