{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Avg Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{handler!=\"/metrics\"}[1m]) / rate(http_request_duration_seconds_count{handler!=\"/metrics\"}[1m]) * 1000) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/docker\"}[1m]))",
     "legendFormat": "container"
    }
   ]
  },
  {
   "title": "Lag by Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag",
     "legendFormat": "group:{{consumergroup}} partition:{{partition}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{topic!=\"__consumer_offsets\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partitions{topic=\"test_topic\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}