{
 "title": "PostgreSQL Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"appdb\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Replication Lag (sec)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_replication_last_replay_seconds",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_cpu_usage_seconds_total{name=~\"app|postgres-master|postgres-replica\"}[1m])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}